### ISSUE TITLE
Versioning issue with standard installation

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/PyDSTool.jl#5]
https://travis-ci.org/JuliaDiffEq/PyDSTool.jl/jobs/333382020#L690
https://ci.appveyor.com/project/ChrisRackauckas/pydstool-jl/build/1.0.58/job/wfhgp6mq30pnt70g#L382

@isuruf do you what could cause this?

**Comment by isuruf** [comment]
Wow, that's one hell of a way to check versions. See https://github.com/robclewley/pydstool/blob/master/PyDSTool/__init__.py#L75
To check that SciPy version >= 0.5, they are checking that the minor version >=5 ignoring the major version which fails because scipy 1.0.0 was released a few months back (And anaconda,inc updated their scipy version recently)

**Comment by tkf** [comment]
> do you think the best way to solve JuliaDiffEq/PyDSTool.jl#5 for now is to just try upper bounding?
>
> --- @ChrisRackauckas in https://github.com/robclewley/pydstool/pull/132#issuecomment-363209070

You mean upper bounding scipy version?  I suppose that works but it's kind of sad...  pydstool also has problem with Python 3 and I made a PR a while ago but it's not merged yet: https://github.com/robclewley/pydstool/pull/125  For my own usage, I ended up merging those branches into a fork and pip-installing it: https://github.com/tkf/pydstool/tree/tkf  You can install it in the conda environment in principle, with something like:

```
PATH/TO/CONDA/ENV/bin/pip install 'https://github.com/tkf/pydstool/archive/tkf.zip#egg=PyDSTool-0.90.2'
```

but I'm not very confident about my patches, especially because the tests are not working...

(BTW, I think the *best* way is to implement the bifurcation tools in Julia. :wink: )

**Comment by ChrisRackauckas** [comment]
It seems like the maintainers are quite absent at that repo. Is there a short term solution?

**Comment by tkf** [comment]
My personal shot-term solution was the fork.  If you want to stick with the official code, downgrading scipy would be the easiest choice.  If you are fine with a dirty-hack evil solution, I guess you can monkey patch `scipy.__version__` while importing pydstool, like this:

```python
import scipy

original_version = scipy.__version__
try:
    scipy.__version__ = '0.9'
    import PyDSTool
finally:
    scipy.__version__ = original_version
```

Once `PyDSTool` is imported in a Python process (meaning that the module is in `sys.modules`).  Re-importing it without that monkey-patch should work.  So, you just need to put the above monkeypatch in `py"""...."""` just before the pyimport stuff.

**Comment by tkf** [comment]
I just noticed that the monkey patch won't work. So it's either fork or downgrading scipy.

**Comment by isuruf** [comment]
You could patch the package in conda-forge. We don't mind adding a patch like that when the upstream is slow in making a release.

**Comment by tkf** [comment]
@isuruf Actually, I found a *super* evil way to make it work https://github.com/JuliaDiffEq/PyDSTool.jl/pull/6/commits/adb051cb6bcd4d3d35bcbf515ab2187688a2674d

This is the worst patch I ever sent...
